print('Hello World')
print()
print(1,2,3,4,5)
print('한글사용')
print(type('안녕'))
print(type("안녕"))
print(type(123))
print('"안녕"이라고 했다.')
print("'안녕'이라고 했다.")
print("\"안녕\"이라고 했다")
print('이름\t나이\t지역')
print('김현아\t20\t강남구')
print('오철수\t25\t서초구')
print("hello"[0])
print("hello"[1])
print("hello"[2])
print("hello"[3])
print("hello"[4])
print('안녕하세요'[1:4])
print(True)
print(10 == 100)
print(10 != 100)
print(10 < 100)
print(10 > 100)
print(10 >= 100)

print("가방" == "가방")
print("가방" == "백")
print("가방" != "백")
print("가방">"백")
print("가방" < "백")